### PR TITLE
Changed the styling of select labels to hide overflow

### PR DESCRIPTION
**Pull request by Adam-Shopfront**

### CODE REVIEW

**Comment by g4ther** [comment]
@Adam-Shopfront Can you put up a screenshot of what this now looks like?

**Comment by Adam-Shopfront** [comment]
Screenshot 2023-01-23 at 8 47 39 am

**Comment by g4ther** [comment]
@Adam-Shopfront So what's the rationale behind this change? I'm just concerned that the vast majority of users aren't going to be able to see the full descriptions anymore

**Comment by Adam-Shopfront** [comment]
Changing it for this [issue](https://onshopfront.atlassian.net/browse/SHOPFRONT-5381). If we don't want to fix it that way, I can see if we can read height from the cellMeasurer

**Pull request closed without merging**
